import React from 'react';
import './TC.css';

const TermsAndConditions = () => {
    return (
        <div className="terms-and-conditions-container">
            <h1 className="page-heading">Our Terms and Conditions</h1>
            <h1 className="page-heading-2">PLEASE READ THIS TERMS OF SERVICE AGREEMENT CAREFULLY. BY USING THIS WEBSITE OR ORDERING PRODUCTS FROM THIS WEBSITE YOU AGREE TO BE BOUND BY ALL OF THE TERMS AND CONDITIONS OF THIS AGREEMENT.</h1>
            <div className="terms-and-conditions-content">
                {/* Your terms and conditions content goes here */}
                <span>Terms of use:<br />

                    The Climeclabs Private Limited (“Climeclabs”) owns and operates this website https://www.climeclabs.com ("Website") having it registered office at Room no.1, 5th floor, SIIEC Office space, Basic Enginering lab building, SRMIST, Kattankulathur, Kancheepuram, TN, India-603203, India (" referred hereinafter as Climeclabs"). For the purpose of these Terms wherever the context so requires "You" or "User" shall mean any natural or legal person who has agreed to become a buyer on our site. The term "We",  Us", "Our" shall mean Climeclabs.<br />
                    The following Terms of Use govern your access and use of this Web Site.  Use of our site includes accessing, browsing, or registering for an account on our site. Also, specific terms and conditions may apply to specific content, data, materials, or information contained on or available through this Web Site (the "Content") and to specific content, data, materials, or information you may upload, submit and/or publish to the Web Site (“User Content”) or transactions concluded through this Web Site. Such specific terms may be in addition to these Terms of Use or, to the extent expressly specified, may supersede these Terms of Use. Please read these terms of use carefully before you start to use our site, as these will apply to your use of our site. We recommend that you may also print a copy of these terms for future reference.<br /><br />
                    This document is an electronic record in terms of the Information Technology Act, 2000 and the rules made there under or any other rules and various other statutes as applicable. This electronic record is generated by a computer system and does not require physical or digital signatures.<br /><br />
                    DEFINITIONS:<br /><br />
                    Agreement" means the terms and conditions as detailed herein including all schedules, appendices, annexures, privacy policy, warranty terms and conditions  etc., and will include the references to this agreement as amended, notated, supplemented, varied or replaced from time to time.<br /><br />
                    www.climeclabs.com web site" means the online shopping platform and the services provided by it owned and operated by Climeclabs which provides a venue to the users to buy the products listed on www.climeclabs.com.<br /><br />
                    "Customer"/"buyer" shall mean the person or any legal entity who makes the offer for sale on climeclabs.com by placing an order for and or purchases any products
                    "Product/Products through the platform of climeclabs.com" means and includes any goods / merchandise / products / services / offers / display items that are uploaded /showcased/displayed on climeclabs.com and the related description, information, procedure, processes, warranties, delivery schedule, etc.] <br /><br />
                    About The Site:<br /><br />
                    The information contained on the website is anticipated to provide broad consumer understanding and knowledge of air purification/ air purifiers for improvement in range general healthy conditions and healthy lifestyle like (If any). We compile information from many sources so it should not be considered complete, exhaustive, or accurate and should never be used in place of sound medical advice or visit to a qualified professional. User is responsible for researching on the information found on this site from the sources. The website or climeclabs make no warranty as to the reliability, accuracy, timeliness, usefulness, or completeness of the information on its web sites, nor any 3rd party sites for which any reference has been made.  Information accessed through these online web sites is provided "AS IS" basis and without warranty, express or implied. All implied warranties of merchantability and fitness for a particular use or purpose are hereby are disclaimed and excluded.<br /><br />
                    This Website may contain links to other websites (the "Linked Sites"), which are not operated by climeclabs has no control over the Linked Sites and accepts no responsibility for them or for any loss or damage that may arise from your use of them. Your use of the Linked Sites will be subject to the terms of use and service contained within each such site.<br /><br />
                </span><br /><br />
                <h1 className="page-heading-2">Acceptance of Terms of Use:</h1>
                <span>By accessing or using this Website you agree and confirm that you confirm that you are a person who can form legally binding contracts under Indian Contract Act, 1872 and you accept these terms of use and that you agree to comply with them. And further to be legally bound by the Terms of Use and all terms and conditions contained or referenced herein or any additional terms and conditions set forth on this Web Site. If you do NOT agree to all of these terms, you must NOT access or use this Web Site.</span><br /><br />
                <h1 className="page-heading-2">Changes:</h1>
                <span>These Terms of Use may be amended by us at any time. Such amended Terms of Use shall be effective upon posting. By continuing to access or use the Web Site after such posting, you will be deemed to have accepted such amendments and updated terms. You are advised to regularly review any applicable terms and conditions.<br /><br />

                    We reserve the right to discontinue or make changes or updates with respect to the Web Site or the Content of the Web Site at any time without prior notice. We reserve the right to restrict, refuse, suspend or terminate access of any person to the Web Site or any part thereof effective immediately without notice at any time and for any reason whatsoever at our sole discretion.
                </span><br /><br />
                <h1 className="page-heading-2">Privacy Policy: </h1>
                <span>Personal information provided or collected through or in connection with this Web Site shall only be used in accordance with our Privacy Policy and these Terms of Use are subject to the Privacy Policy as posted on this Web Site. <a href='/TC'>www.climeclabs.com/TC</a></span><br /><br />
                <h1 className="page-heading-2">Age Restriction: </h1>
                <span>You must be at least 18 (eighteen) years of age in order to use the website or for the services contained herein. By using the website, you hereby represent and warrant that you are at least 18 years of age and legally agree to these terms of services/ We assume no liability or responsibility for any such misrepresentation of your age</span><br /><br />
                <h1 className="page-heading-2">Disclaimers: </h1>
                <span>All information (including, software, services, products, text, graphics, pictures, and other materials) provided by us is provided "as is" basis and "as available". We hereby expressly disclaim to extent permitted by law any representations or warranties of any kind, express or implied, including fitness for any particular purpose, non-infringement, warranties of merchantability, or as to the operation of this web site, the content or user content. We make no warranties or representations that the Web Site will meet your needs or requirements or that the website will be uninterrupted, secure, or error free, or for the results that may be obtained from the use of the website. We make no warranties that the information (including any information and materials on this Web Site) will be correct, accurate, complete, reliable, or otherwise meeting your requirements.</span><br /><br />
                <span>Your use of any information or materials on the website or otherwise obtained through use of this website is entirely at your own risk and We shall not be made liable for such use. Climeclabs does not provide any warranties against mistakes, errors or inaccuracies of information, content data, materials, substance of the website, any unauthorized access, any bugs, viruses, or the alike issues which may be transmitted to or through the website by any third party, any interruption or suspension of transmission to or from the website, any defamatory, offensive, or illegal conduct of any third party or service user or service provider, or  for any direct, indirect, punitive, incidental, specific, consequential damages (including, without limitation, damages for loss of business opportunities or loss of profits) arising in contract, tort or otherwise from the use of or inability to use the Site, or any of its contents, or from any act or omissions as a result of using the Site or  use of any data, content, information, materials, substance of the website or submitted content posted, emailed, transmitted, or otherwise made available via the website. Climeclabs does not endorse, warrant, guarantee, or assume responsibility for any product or service advertised or offered by a third party through the website or any linked site.</span><br /><br />
                <span>As it is understood by you that certain links on the Site redirects or leads to resources located on servers maintained and operated by third parties which are not controlled by us. You agree and understand that by visit to such site, downloading or otherwise obtaining any material from use of linked website(s) shall not make us liable and we accept no responsibility or liability for the authenticity/availability of any of the goods/services/or for any damage, loss or harm, direct or consequential or any violation of local or international laws that may be incurred by your visit and/or transaction/s on these sites. You will be solely responsible for any damage to your computer system or loss of data that results from the download of any such material.</span><br /><br />
                <h1 className="page-heading-2">Plant usage Disclaimer: </h1>
                <span>We assume no responsibility or warranty for providing you information regarding the plants or similar products which may be used to augment the capacity of the air purifier or the air purification process. That you are solely responsible for choosing and using any type of plant on the Air purifier and in case the user is uncertain about possible sensitivity or usage of certain plants species, which may cause allergy/sensitivity in susceptible individuals then in that case you and user shall be responsible for usage of such species. Information regarding the compatibility of the plant species or similar products appearing on the Website or provided along with the product/ or with the information booklet or under any interaction session  is and will be intended to be used and taken as  a general advise only and We do not warrant or take responsibility for each individual user, nor it should be interpreted as such an advice being specific to the user as each user may be or may not be allergic to individual species of plants or similar products. It is recommended to always seek the advice of such qualified health professional.  (Need to take information).</span><br /><br />
                <h1 className="page-heading-2">User Obligation and Registration: </h1>
                <span>As a user of this website, you may be asked to register with us and provide private information. When such registration happens, a unique identifier shall be chosen by you, which may be your email address/any other handle, along with a password. You may be asked to provide other personal and private information including but not limited to name, address, etc.  You will be responsible for ensuring the accuracy of this information, for maintaining the safety and security of your identifying information, for all activities that occur under your account or password.
                    We reserve the right to change your username or delete your submitted content to the Web Site or refuse or cancel your registration at our sole discretion. If you become aware of any suspicious or unauthorized conduct concerning your account, user name and/or password, you agree to contact us immediately.
                </span><br /><br />
                <h1 className="page-heading-2">Pricing and Availability (Need To Add For Taxes): </h1>
                <span>The prices of the Products will be as quoted on our site from time to time, whilst we take all reasonable care that the details, descriptions and prices which appear on this Website are accurate, it is possible that errors may occur. If we discover an error in the price of any goods which you have ordered we will inform you of this as soon as possible and give you the option of reconfirming your order at the correct price or cancelling it. If we are unable to contact you we will treat the order as cancelled. If you cancel the order and you have already paid for the goods, you will receive a full refund.<br /><br />
                    Delivery costs will be charged in addition; such additional charges are clearly displayed where applicable and included in the 'Total Cost'.<br /><br />
                    Further the Prices for our Product(s) may change from time to time, but changes will not affect any order which we have confirmed with a Dispatch Confirmation.<br /><br />
                    Please note that if the pricing error is obvious and unmistakeable and could have reasonably been recognised by you or reasonable person, as a mispricing, we do not have to provide the Products to you at the incorrect (lower) price.
                </span><br /><br />
                <h1 className="page-heading-2">Payment And Fees: </h1>
                <span>Payment can be made in Indian Rupees by different modes including, cash of delivery (to a certain value), internet banking,(Any cards specific),  UPI, Wallets, card on delivery as mentioned by Us from time to time and such other conditions which may be applicable on the mode of payment including without limitation, for No Cost EMI and Cash on Delivery. We, at our sole discretion, reserve the right to add or remove or modify the terms and conditions for such payment options without prior notice. Notwithstanding the above, the payment method options shall be subject all statutory rules and regulation along with the guidelines of facility providers.<br /><br />
                    You acknowledge that while availing any of the payment methods available on our Site, you shall be completely responsible for all transaction and We assume no liability, whatsoever in respect of any loss or damage arising directly or indirectly to You.<br /><br />
                    In case of cash on delivery or card on delivery, the order amount has to be paid in full before receiving the package and signing the delivery sheet. The package can be opened only after the full payment is made to Us or the concerned delivery agent.<br /><br />
                    We reserve our right to refuse to sell the products listed on the website at our sole discretion to anyone for any reason whatsoever.<br /><br />
                </span>
                <h1 className="page-heading-2">Acceptable Use And Contribution: </h1>
                <span>It is agreed by you that you will not to use the Website or Services for any unlawful purpose or any purpose prohibited under this clause. You agree not to use the Website or Services in any way that could damage the Website, Services or general business of the Climeclabs.<br /><br /></span>
                <span>You further agree not to use the Website or Services:</span><br /><br />
                <ul style={{ textAlign: "left" }}>
                    <li>To harass, abuse, or threaten others or otherwise violate any person’s legal rights;</li>
                    <li>To violate any intellectual property rights of the Climeclabs or any third party;</li>
                    <li>To upload or otherwise disseminate any computer viruses or other software that may damage the property of another;</li>
                    <li>To perpetrate any fraud;</li>
                    <li>To engage in or create any unlawful gambling, sweepstakes, or pyramid scheme;</li>
                    <li>To publish or distribute any obscene or defamatory material;</li>
                    <li>To publish or distribute any material that incites violence, hate or discrimination towards any group;
                    </li>
                    <li>To unlawfully gather information about others.</li>
                </ul><br />
                <span>You are prohibited from using the site or its content: (a) for any unlawful purpose; (b) to solicit others to perform or participate in any unlawful acts; (c) to infringe on any third party’s intellectual property or proprietary rights, or rights of publicity or privacy, whether knowingly or unknowingly; (d) to violate any local, federal or international law, statute, ordinance or regulation; (e) to harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate based on gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability; (f) to submit false or misleading information or any content which is defamatory, libelous, threatening, unlawful, harassing, indecent, abusive, obscene, or lewd and lascivious or pornographic, or exploits minors in any way or assists in human trafficking or content that would violate rights of publicity and/or privacy or that would violate any law; (g) to upload or transmit viruses or any other type of malicious code that will or may be used in any way that will affect the functionality or operation of the Service or of any related website, other websites, or the Internet; (h) to collect or track the personal information of others; (i) to damage, disable, overburden, or impair the Website or any other party’s use of the Website; (j) to spam, phish, pretext, spider, crawl, or scrape; (j) for any obscene or immoral purpose; or (k) to interfere with or circumvent the security features of the Service or any related website, other websites, or the Internet; (I) to personally threaten or has the effect of personally threatening other Users. We reserve the right to terminate your use of the Service or any related website for violating any of the prohibited uses. The Company has the full authority to review all content posted by Users on the Website. You acknowledge that the Website is not responsible or liable and does not control the content of any information that may be posted to the Website by You or other User of the Website and you are solely responsible for the same. You agree that You shall not upload, post, or transmit any content that you do not have a right to make available (such as, the intellectual property of another party).<br /><br />
                </span>
                <span>You agree to comply with all applicable laws, statutes and regulations concerning your use of the Website and further agree that you will not transmit any information, data, text, files, links, software, chats, communication or other materials that is abusive, invasive of another’s privacy, harassing, defamatory, vulgar, obscene, unlawful, false, misleading, harmful, threatening, hateful or racially or otherwise objectionable, including without limitation material of any kind or nature that encourages conduct that could constitute a criminal offense, give rise to civil liability or otherwise violate any applicable local, state, provincial, national, or international law or regulation, or encourage the use of controlled substances.</span><br /><br />
                <span>We may, but have no obligation to, monitor, edit or remove content that we determine in our sole discretion are unlawful, offensive, threatening, libellous, defamatory, pornographic, obscene or otherwise objectionable or violates any party’s intellectual property or these Terms of Service.</span><br /><br />
                <span>You may not use our products for any illegal or unauthorized purpose nor may you, in the use of the Service, violate any laws in your jurisdiction (including but not limited to copyright laws).</span><br /><br />
                <h1 className="page-heading">COMMUNICATION: </h1>
                <span>You understand that each time use the Website in any manner, you agree to these Terms. By agreeing to these Terms, you acknowledge that you are interested in availing and purchasing the Services that you have selected and consent to receive communications via phone or electronic records from the Website including e-mail messages telling you about products and services offered through the Website (or its affiliates and partners) and understanding your requirements. Communication can also be by posting any notices on the Website. You agree that the communications sent to You by the Website shall not be construed as spam or bulk under any law prevailing in any country where such communication is received.</span><br /><br />
                <h1 className="page-heading-2">Shipping Return, Refund And Delivery Policy: </h1>
                <span>All items purchased directly through Climeclabs or its website can be returned/exchanged within 7 days of purchase only in case there is a defect/fault/break in the shipped product. While purchasing the product, you agree to provide us with valid email, shipping address and bill information. We reserve the right to reject or cancel an order for any reason, including errors or omissions in the information provided to us by you. In case the cancellation of order is done after the realization of payment, We will issue a refund to You for the amount of the purchase price.  It may be the case that certain additional information is required before confirming a sale and we reserve our right to place any additional restrictions on the sale of any of Our products. You agree to ensure payment for any items purchased by you from us and that prices are subject to change from time to time.</span><br /><br />
                <span>Air purifier filters can only be returned if the item has not been used. Shipping and handling costs are not refundable. Consumers are responsible for paying shipping costs to return the order to our company unless there was an error on our part related to the order, or the product arrived damaged or defective. In case of any concerns you can contact on 9123580564.</span><br /><br />
                <h1 className="page-heading-2">Limitation of Liability: </h1>
                <span>In no event shall climeclabs, its officers, managers, members, licensors, service professionals brand licensees or suppliers, attorneys agents,  be liable to you for any direct, indirect, consequential, punitive, special or incidental or other damages including but not limited to (loss of business, revenue, profits, use, data or other economic advantage) whatsoever resulting from any  resulting from, arising out of or in connection with the access, use of, or inability to access or use this web site, the content or the user content, even if climeclabs has been advised of the possibility of such damages except to the extent such damages arise as a result of fraud or fraudulent misrepresentation on the part of climeclabs.</span><br /><br />
                <span>Our total liability to You in respect of losses arising under or in connection with the Contract, whether in contract, tort (including negligence), breach of statutory duty, or otherwise, shall in no circumstances exceed the purchase price of the Product.</span><br /><br />
                <span>Furthermore, we are not liable even if we've been negligent and/or if we or our authorized representative(s) have been advised of the possibility of such damages. No advice or information, whether oral or written, obtained by you by any means from us shall create any warranty of any kind.</span><br /><br />
                <span>However, in certain countries it may be possible that law may not allow exclusions or limitations of liability or incidental or consequential damages or any of the disclaimers of warranties, then such exclusions or limitations will not apply to you but only to the extent such exclusions or limitations are not allowed. But in any event, our liability to you for all losses, damages, injuries, and claims of every kind (whether the damages are claimed under the terms of a contract, or they're claimed to be caused by negligence or other wrongful conduct, or they're claimed under any other legal theory) will not be greater than purchase price of the Products.
                </span><br /><br />
                <h1 className="page-heading-2">Third Party Content/Software: </h1>
                <span>We shall not be held responsible for the content or information of any website owned/operated by a third party that may be linked to our Web Site via hyperlink, does not matter if the hyperlink is provided by the Web Site or by a third party as per the Terms of Use. Any such link available on our website shall not be treated as an endorsement of such other site and further we do not warrant about the accuracy, timeliness, or correctness of the content of any such site.
                </span><br /><br />
                <h1 className="page-heading-2">Linking to our site and Limited Permission to Copy: </h1>
                <span>You may link to our home page, provided you do so in a way that is fair and legal and does not damage our reputation or take advantage of it. Not link must be made/established in a way to suggest or imply any form of association, approval or endorsement on our part which does not exists. No link shall be established between the websites, not owned by you. We reserve the right to withdraw linking permission without notice. We only allow you to print or download extracts from these website pages only for your personal non-commercial use.  No part of the Site may be transmitted or reproduced or stored , may not be stored or linked to any other website or links in any form included in any public or private electronic retrieval system or service without our prior written permission.</span><br /><br />
                <span>Any software made available for downloading from or through this Web Site is licensed subject to the terms of any applicable license agreement. Except as set forth in the applicable license agreement, the software is made available for use by end users only and any further copying, reproduction or redistribution of the software is expressly prohibited. Warranties, if any, with respect to such software shall only apply as expressly set forth in the applicable license agreement. We hereby expressly disclaims all further representations and warranties of any kind, express or implied, including warranties of merchantability, fitness for any particular purpose or non-infringement with respect to the software.
                </span><br /><br />
                <h1 className="page-heading-2">Intellectual Property, Software And Content: </h1>
                <span>Unless otherwise stated, You agree that all the intellectual property rights in all software and content (including all copyrights, trademarks, trade-secrets, patents, photographic images, texts, and videos) made available to you on or through this Website is the property of Climec Labs. You may store, print and display the content supplied solely for your own personal use. You are not permitted to publish, manipulate, distribute or otherwise reproduce, in any format, any of the content or copies of the content supplied to you or which appears on this Website, nor may you use any such content in connection with any business or commercial enterprise. You must not use any part of the content on our site for commercial purposes without obtaining a licence to do so from us or our licensors. If you print off, copy or download any part of our site in breach of these terms of use, your right to use our site will cease immediately and you must, at our option, return or destroy any copies of the materials you have made.</span><br /><br />
                <span>Any infringement shall be vigorously prosecuted and pursued to the fullest extent permitted by law.</span><br /><br />
                <span>In case, you believe that your intellectual rights have been infringed or otherwise violated by the posting of any such information or media by another of our users, you can inform us at the earliest.</span><br /><br />
                <h1 className="page-heading-2">Proprietary Rights in the Web Site: </h1>
                <span>This Web Site herein is public by nature and any information which may be submitted by use of the website shall be considered as non-confidential. You acknowledge in case an invention or content or research is personified in any User Content provided by you shall constitute a "publication" of such invention under applicable patent laws.</span><br /><br />
                <span>You acknowledge that any User Content submitted and/or discussed on the Web Site may be the subject of patents, copyrights, trademarks and other intellectual property rights of climeclabs, its subsidiaries, affiliates, brand licensees, other partners or third parties. If you consider exploiting any ideas, proposals, suggestions, or solutions or other User Content submitted to the Web Site, you are responsible to undertake appropriate intellectual property clearance before engaging in any exploitative conduct.
                </span><br /><br />
                <h1 className="page-heading">LICENSE TO USE WEBSITE: </h1>
                <span>We may provide You with certain information as a result of Your use of the Website or Services. Such information may include, but is not limited to, documentation, data, or information developed by the Us, and other materials which may assist in Your use of the Website. Subject to these Terms of Service, we grant you a non-exclusive, limited, non-transferable and revocable license to use our Materials solely in connection with Your use of the Website and Services. Our Materials may not be used for any other purpose and this license terminates upon Your cessation of use of the Website or Services or at the termination of these Terms of Service.</span><br /><br />
                <h1 className="page-heading">REVERSE ENGINEERING AND SECURITY: </h1>
                <span>You unconditionally undertake not to take or execute the action of reverse engineering or make any attempt to reverse engineer or disassemble any code or software from the website or violate the security of the website through use of any unauthorised access, circumvention of encryption or other tools etc. Moreover, You also undertake no to reverse engineer or make attempt to reverse engineer or disassemble our products.</span><br /><br />
                <h1 className="page-heading-2">Indemnification: </h1>
                <span>
                    You agree to indemnify, defend and hold harmless climeclabs Pvt. Ltd, its  affiliates, brand licensees, other partners and suppliers and each of their respective officers, directors, employees, shareholders, legal representatives, agents, successors and assigns, from and against any damages, liabilities, costs and expenses (including reasonable attorneys' and professionals' fees and litigation costs) that arise out of misuse of the website or services  or transmission of any message, data, material or any other User Content  which may you submit on the Web Site or any violation of these Terms of Use of this website.
                </span><br /><br />
                <h1 className="page-heading-2">Term Termination and Suspension: </h1>
                <span>
                    We retain the right to terminate these terms with you at any time for any reason with or without any cause. We specifically retain the right to terminate the terms of services in case of any breach of the terms by you or your use of the website including but not limited to the breach of intellectual property rights of climeclabs or a third party, failure of comply with the applicable and the extant laws Or to comply with any other legal obligations or by publishing defamatory or illegal material. In such case, if any registered account is maintained with us, we shall have the right to terminate the same. You also have the right to terminate these terms of service at any time by contacting us and requesting for the termination through the available mode. Notwithstanding anything, any provision to survive such termination shall survive.
                </span><br /><br />
                <h1 className="page-heading">Warranty Terms: </h1>
                <span>We provide a 1 year warranty on the goods sold by us.<br /><br /></span>
                <span>WHAT THIS WARRANTY COVERS</span><br /><br />
                <ol style={{ textAlign: "left" }}>
                    <li>Repairs under warranty shall be carried out by an authorized service personnel only. The details of call center are mentioned in the warranty card.</li>
                    <li>In case of repairs or replacement of any part/s of the unit or replacement of the unit as deemed by Climec Labs, this warranty will thereafter continue and remain in force only for the unexpired period of the warranty.</li><br />
                    <span>Parts covered: This warranty contract covers repair / replacement of functional, electronic and Electrical parts within warranty period. Any damage part/ accessory case to be reported at the time of installation to claim replacement.</span><br /><br />
                    <li>Replacement of parts would be purely at the discretion of Climec Labs alone. In case the replacement of the entire unit is being made, (subject to the sole discretion of Climec Labs), the same model shall be replaced and in the event such model has been discontinued, it shall be replaced with the model equivalent as deemed by Climec Labs.</li>
                    <li> In event of repair Climec Labs shall endeavor to use new parts however in any case fresh parts are not available then Climec Labs will have every right to use refurbished parts. The warranty on replacement model / Refurbished part shall remain in force only for the unexpired period of the warranty based on original purchase.</li>
                    <li>The company or its Authorized Service Center reserves the right to retain any part/s or component replaced at its discretion, in the event of a defect being noticed in the equipment during warranty period.</li>
                    <li>If any colored internal or external components are replaced, there will be commitment to ensure that the shades match with the original or other components. The replaced shades, patterns, tints may vary from the customer’s unit due to continuous usage of the unit. Any matching components changed at customer’s request will be on chargeable basis except the component which actually needed.</li>
                    <li>This warranty will automatically terminate on the expiry of the warranty period as specified above, even if Climec Labs product may not be in use for any time during the warranty period for any reason.</li>
                    <li> In case of any unpredicted situation and spares not being available, Climec Labs’s prevailing depreciation policy (subject to the sole discretion of Climec Labs & could be change without prior notice) will be applied on the product as a solution.</li>
                    <li>Only courts in state of Chennai and places where Climec Labs has its branch office shall have the jurisdiction for settling any claims, disputes arising under the warranty.</li>
                    <li> In warranty Blower Replacement:<br /><ul><li>In case of blower failure during 1st year of product repair warranty, Climec Labs shall supply free replacement blower against submission of valid Invoice supported with job completion report duly acknowledged by customer as per company norms & policy.</li>
                        <li>For blower failing after the 1st year of product repair warranty and during the additional period of blower warranty, Climec Labs shall supply only free replacement of blower whereas the charges towards labor and transportation have to be collected from customer.</li></ul></li>
                </ol><br />
                <h1 className="page-heading">WHAT THIS WARRANTY  DON’T COVER: </h1>
                <ol style={{ textAlign: "left" }}>
                    <li>Visiting charges of the service engineer /unit/ part/ transportation charges/ installation for units.</li>
                    <li> All expenses incurred in collecting the units or parts thereof from the company’s authorized service center, as well as expenses incurred with deputizing of service personnel / technicians towards conveyance and other incidentals etc. will be borne by the customer and the same shall be at the customer risks & Consequences. Local Charges for transportation and handling charges may vary from location to location. Customers are advised to verify before.</li>
                    <li>In case the customer desires to bring the unit on its own to the authorized service centre, Re re-installation or un-installation of product based on customer demand. Packing material if used will also be on chargeable basis.</li>
                    <li> Damage resulting from operating the product in a corrosive atmosphere or contrary to the instructions outlined in the products owner manual. Labor charges will also be borne by customer.</li>
                    <li>Damage to the product caused by accidents, pests and vermin, lightning, wind fire, floods, or acts of God.</li>
                    <li>Damage resulting from misuse, abuse, improper installation, repair or maintenance. Improper repair includes use of parts not approved or specified by Climec Labs.</li>
                    <li>Damage or Failure caused by unauthorized modification or alteration or if it is used for other than the intended purpose or any water leakage where the unit was not properly installed.</li>
                    <li>Damage or Failure caused by incorrect electrical current, voltage or inadequate electrical services, commercial or industrial use, or use of spurious/fake accessories or components, or cleaning products that Climec Labs do not approve.</li>
                    <li>Damage caused by transportation and handling, including scratches, dents, chips, and/or other damage to the finish of your product, unless such damage results from defect in materials or workmanship and is reported within seven days of delivery.</li>
                    <li>Damage or missing items to any display, open box, discounted or refurbished product.</li>
                    <li>Damage to the product if customer gets the product repaired from unauthorized dealer/Person </li>
                    <li>On removal, tampering or alteration of any serial number/identification labels on the machine or any of its components.</li>
                    <li>Any obligation to carry out the repair in specified time period, while every effort will be made from Climec Labs or its authorized service center side to carry out the repair at the earliest.</li>
                    <li>Free accessories provided external to the product.</li>
                    <li>No Warranty will be offered for Discounted or refurbished product sold directly or indirectly by Climec Labs.</li>
                    <li>Free installation not applicable for products where DOP is more than 3 months.</li>
                    <li>Free gifts given along with product by Dealer.</li>
                </ol>
                <h1 className="page-heading">OW (Out warranty) Terms & Conditions: </h1>
                <ol style={{ textAlign: "left" }}>
                    <li>Field/Home service is available on the air purifier marketed and sold by Climec Labs  Research Private Limited.</li>
                    <li> If customer refuses for Installation then Site inspection charges apply.</li>
                    <li>Repair warranty with labor & with part.</li>
                    <li>If a part is replaced under warranty, warranty on same expires as per overall unit’s warranty.</li>
                    <li>All service charges are exclusive of all taxes.</li>
                    <li>Service tax as Applicable as of 1st of Jun-2021.</li>
                    <li> In case the customer complaint requires ASC to travel beyond the municipal limits of the city, then customer has to bear the additional travel expenses over and above the fixed service charges.
                    </li>
                    <li>Transportation cost to be charged, If the product needs to be repaired from other city/country (Actual Cost).</li>
                    <li>For call back of product to ASC workshop, product transportation charges to be charged.</li></ol><br /><br />
                <span>Policy 1 (e.1): Replacement/Refund policy including DOA– Guidelines / Process flow / Approval path If the product cannot be repaired due to non-availability of spare parts, or repeated failure or high repair cost replacement or refund is offered to a customer. Exception DOA damage product received by customer.</span><br /><br />
                <h1 className="page-heading">Policy </h1>
                <ol style={{ textAlign: "left" }}>
                    <li> If a Product fails to perform during the warranty period, extended warranty period or out of warranty period and cannot be repaired, then the Customer Service department shall assess the facts and take any of the following actions:</li>
                    <ul><li>Replace it with the same model.</li>
                        <li> Replace it with the upgraded model (in case if same model is discontinued or not available)</li>
                        <li>Make a refund (in case if customer shows his unwillingness to accept replacement).</li></ul>
                    <li>Reasons for return could be as below:<ul><li> DOA (Dead on Arrival)</li>
                        <li>Quality issue</li>
                        <li>Part not available – discontinued/ long ETA/ not available in same location</li>
                        <li>Repeat repair: 3 or more times failure of similar type within 6 months</li>
                        <li>Repair delay: product not repaired within 30 days due to ASC negligence. Penalty applicable (cost of replacement) to ASC</li>
                        <li>B.E.R. (Beyond economical repairs): applicable when part cost is high equivalent to 75% or more of product DP</li>
                        <ul>Court order.</ul>
                    </ul></li>
                    <li>Replacements / Refunds shall be subject to Depreciation policy and shall be based on the price on Invoice to customer.</li>
                    <li>Refund shall not be applicable for System Solution Division products.</li>
                    <li> DOA Policy: (Dead on Arrival) applicable for end consumer only</li>
                    <ul><li>Applicable if the product fails with in stipulated time frame of 7/ 30 days from DOP (Customer Invoice) & customer refuses for repair</li>
                        <li>DOA bifurcates into Technical & Non-Technical Issues in the product (Technical – Dead / Any part defect & Non-Technical – Broken / dent / aesthetic & cosmetic failure)</li>
                        <li>Applicable on vSure air purifier.</li><br /></ul>
                    <span>CS department shall assess the facts and take any of the following actions:</span><br /><br />
                    <ul><li>Replace it with the same model.</li>
                        <li>Replace it with alternate/ upgraded model (in case same model is not available or discontinued)</li>
                        <li>Customer is willing to upgrade to higher model by paying differential amount (D.P – 10%)</li>
                        <li> Make a refund (in case if customer shows his unwillingness to accept replacement)</li><br />
                    </ul>
                    <li>Depreciation Policy:</li><br />
                    <ul>Refer below matrix for Depreciation rates</ul><br />
                    <span>Consumers Sales division</span><br /><br />
                    <table className="custom-table">
                        <thead>
                            <tr>
                                <th>Ageing from DOP</th>
                                <th>Air Purifier</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>0 – 6 Month</td>
                                <td>0%</td>
                            </tr>
                            <tr>
                                <td>6 – 9 Month</td>
                                <td>25%</td>
                            </tr>
                            <tr>
                                <td>9 – 12 Month</td>
                                <td>50%</td>
                            </tr>
                            <tr>
                                <td>More than 12 Month</td>
                                <td>100%</td>
                            </tr>
                        </tbody>
                    </table>
                    <br /><br />
                    <li>For promotional warranty replacement / refund case depreciation will be applicable based on the standard warranty period of the product only.</li>
                    <li>In case of manufacturing defects (Crack on body/Internal break in air purifier), depreciation shall not be applicable for two years from the date of purchase on Invoice.</li>
                    <li>Following documents shall be required for accepting customer request:</li>
                    <ul><li>Job sheet signed by customer
                    </li>
                        <li>Copy of Original Invoice</li>
                        <li>Warranty Card/Extended warranty card (Optional)</li>
                        <li>Approval form</li>
                    </ul><br />
                    <li>In case of Refund:</li>
                    <ul>
                        <li>All of the above documents</li>
                        <li>Cancelled Cheque</li>
                        <li>Photo ID proof of customer</li>
                        <li>Letter of satisfaction (LOS)</li>
                        <ul>
                            <li>
                                LOS is mandatory for all refund cases.
                            </li>
                            <li>LOS is required for replacement cases.</li>
                        </ul>
                    </ul>
                    <br />
                    <li>Defective product shall be lifted back from the customer:</li><br />
                    <table className="custom-table">
                        <thead>
                            <tr>
                                <th>Case</th>
                                <th>Department responsible</th>
                                <th>Event</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Replacement</td>
                                <td>Logistics</td>
                                <td>At the time of handing over new product</td>
                            </tr>
                            <tr>
                                <td>Refund</td>
                                <td>Customer service</td>
                                <td>At the time of handing over the cheque</td>
                            </tr>
                        </tbody>
                    </table><br />
                    <li>Warranty norm for replaced/ upgraded product: The unit replaced will carry standard warranty from the date of delivery (Climec Labs  Challan date) or balance time as per invoice, whichever is higher.</li>
                    <li>In case of any problem/ defect in air purifier/ accessories supplied along with replaced product, same to be reported within 7 days of delivery of product.</li>
                </ol>
                <h1 className="page-heading">PROCEDURE </h1>
                <ul style={{ textAlign: "left" }}>
                    <li>Part Failure: After completion of standard product warranty [Under extended warranty time frame]</li>
                    <li>Repairable: Parts are available and Product to be repaired as In warranty terms & condition as only parts will be FOC and labor will be charged from customer
                    </li>
                    <li>Non-Repairable: Parts not available then we will offer replacement / refund with the standard depreciation policy (As per the proposed Policy)</li>
                    <li>Non-Part Failure: After completion of standard product warranty [Under extended warranty time frame]</li>
                    <li>Transportation cost will be charged as per the standard product charge matrix from customers</li>
                </ul>
                <h1 className="page-heading-2">Terms & Conditions</h1>
                <ul style={{ textAlign: "left" }}>
                    <li>Proposed depreciation policy on promotional warranty will include extended warranty on the product sold for previous years (as per the above proposed policy)</li>
                    <li>Promotional warranty offers on special parts (Ex – Blowers, Filters, Disinfecting bulbs) will be applicable on the parts replacement only. Labor charges will be borne by the customer.</li>
                    <li>Depreciation will not be applicable for 24 Months from DOP in case of any quality issue / manufacturing defect after 24 months the deprecation will be applicable as per the standard depreciation policy (As proposed policy)</li>
                    <li>In case of high cost of repair depreciation to be applied for customer satisfaction. (as per the above proposed policy)</li>
                    <li>Any deviation to the above policy is as per the Service HOD discretion
                    </li>
                </ul>
                <h1 className="page-heading-2">Dispute Resolution</h1>
                <span>These Terms of Use shall be governed by and construed in accordance with the laws of the state of India. You agree to the exclusive jurisdiction of the courts in Chennai, India for any disputes, claim or cause of action arising out of, or relating to or in connection with these Terms of Use or your use of this Web Site, including any disputes relating to the existence or validity of these Terms of Use, provided that you agree to submit any such disputes, claims or causes of action exclusively to the courts of Chennai, India.</span><br /><br />
                <h1 className="page-heading-2">Severability</h1>
                <span>If any provision of these Terms of Use is held to be invalid or unenforceable, then the invalid or unenforceable provision will be replaced by a valid, enforceable provision that most closely matches the intent of the original provision and the remaining provisions shall be enforced and the remaining provisions of these terms shall remain valid and enforceable.</span><br /><br />
                <h1 className="page-heading-2">No Waiver</h1>
                <span>
                    No failure on our part to enforce any part of these Terms of Use shall constitute a waiver of any of our rights under these Terms of Use, whether for past or future actions on the part of any person. Waiver of any part or sub-part of these terms of service will not constitute a waiver of any other part of sub part
                </span><br /><br />
                <h1 className="page-heading-2">Headings</h1>
                <span>The headings of the sections of the Terms of Use are inserted for convenience only and shall not constitute a part hereof or affect in any way the meaning or interpretation of the Terms of Use.</span><br /><br />
                <h1 className="page-heading-2">No agency or partnership</h1>
                <span>No agency, partnership, joint venture, or employment is created as a result of the Terms of Use or your use of any part of the Website. You do not have any authority whatsoever to bind climeclabs in any respect. Neither climeclabs nor any users of the Website may direct or control the day-to-day activities of the others or create or assume any obligation on behalf of the other.</span><br /><br />
                <h1 className="page-heading">ENTIRE AGREEMENT</h1>
                <span>This Agreement constitutes the entire understanding between the Parties with respect to any and all use of this Website. This Agreement supersedes and replaces all prior or contemporaneous agreements or understandings, written or oral, regarding the use of this Website.</span><br /><br />
            </div>
        </div>
    );
};

export default TermsAndConditions;
